apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-data
  namespace: pihole
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
        - name: pihole
          image: pihole/pihole:2026.05.0
          env:
            - name: TZ
              value: Europe/Madrid
            - name: FTLCONF_dns_listeningMode
              value: ALL
            - name: FTLCONF_webserver_api_password
              valueFrom:
                secretKeyRef:
                  name: pihole-password
                  key: password
          ports:
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: web
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /etc/pihole
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pihole-data
---
apiVersion: v1
kind: Service
metadata:
  name: pihole
  namespace: pihole
  annotations:
    metallb.io/loadBalancerIPs: 192.168.1.99
spec:
  type: LoadBalancer
  selector:
    app: pihole
  ports:
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: web
      port: 80
      targetPort: 80
      protocol: TCP
